SUPPORTED_LANGUAGES = {
    "en": {"name": "English", "asr": "whisper", "nmt": "nllb-200", "tts": "xtts_v2"},
    "pt": {"name": "Português", "asr": "whisper", "nmt": "nllb-200", "tts": "xtts_v2"},
    "es": {"name": "Español", "asr": "whisper", "nmt": "nllb-200", "tts": "xtts_v2"},
    "fr": {"name": "Français", "asr": "whisper", "nmt": "nllb-200", "tts": "xtts_v2"},
    "de": {"name": "Deutsch", "asr": "whisper", "nmt": "nllb-200", "tts": "xtts_v2"},
    "it": {"name": "Italiano", "asr": "whisper", "nmt": "nllb-200", "tts": "xtts_v2"},
    "nl": {"name": "Nederlands", "asr": "whisper", "nmt": "nllb-200", "tts": "xtts_v2"},
    "ru": {"name": "Русский", "asr": "whisper", "nmt": "nllb-200", "tts": "xtts_v2"},
    "uk": {"name": "Українська", "asr": "whisper", "nmt": "nllb-200", "tts": "xtts_v2"},
    "pl": {"name": "Polski", "asr": "whisper", "nmt": "nllb-200", "tts": "xtts_v2"},
    "cs": {"name": "Čeština", "asr": "whisper", "nmt": "nllb-200", "tts": "xtts_v2"},
    "sv": {"name": "Svenska", "asr": "whisper", "nmt": "nllb-200", "tts": "xtts_v2"},
    "da": {"name": "Dansk", "asr": "whisper", "nmt": "nllb-200", "tts": "xtts_v2"},
    "no": {"name": "Norsk", "asr": "whisper", "nmt": "nllb-200", "tts": "xtts_v2"},
    "fi": {"name": "Suomi", "asr": "whisper", "nmt": "nllb-200", "tts": "xtts_v2"},
    "tr": {"name": "Türkçe", "asr": "whisper", "nmt": "nllb-200", "tts": "xtts_v2"},
    "ar": {"name": "العربية", "asr": "whisper", "nmt": "nllb-200", "tts": "xtts_v2"},
    "he": {"name": "עברית", "asr": "whisper", "nmt": "nllb-200", "tts": "xtts_v2"},
    "fa": {"name": "فارسی", "asr": "whisper", "nmt": "nllb-200", "tts": "xtts_v2"},
    "hi": {"name": "हिन्दी", "asr": "whisper", "nmt": "nllb-200", "tts": "xtts_v2"},
    "bn": {"name": "বাংলা", "asr": "whisper", "nmt": "nllb-200", "tts": "xtts_v2"},
    "zh": {"name": "中文", "asr": "whisper", "nmt": "nllb-200", "tts": "xtts_v2"},
    "ja": {"name": "日本語", "asr": "whisper", "nmt": "nllb-200", "tts": "xtts_v2"},
    "ko": {"name": "한국어", "asr": "whisper", "nmt": "nllb-200", "tts": "xtts_v2"},
    "id": {"name": "Bahasa Indonesia", "asr": "whisper", "nmt": "nllb-200", "tts": "xtts_v2"},
}
